database:
  type: SQLITE

  mysql:
    host: localhost
    port: '3306'
    user: root
    password: ''
    database: minecraft
    pool:
      minimumIdle: 10
      maximumPoolSize: 30
      connectionTimeout: 10000
      idleTimeout: 600000
      maxLifetime: 1800000
      leakDetectionThreshold: 0
      properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

  redis:
    enabled: false
    host: localhost
    port: 6379
    password: '1234'
